var _cs='';
_cs += "<div class=\"super\" id=\"adv_top_user\" style=\"display:none\">";
_cs += "	<div class=\"user\">		<div class=\"left\"><font color=\"green\"></font> 欢迎您进入拍拍店长   [<a href=\"#\" target=\"_blank\">退出</a>]</div>		<div class=\"right\">			<a href=\"#\">拍拍店长</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">特推广</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">苹果推广</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">微博推广</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">营销推广专家</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\">短信提醒</a>		</div>	</div>";
_cs += "</div>";
_cs += "<div class=\"super2\">";
_cs += "	<div class=\"top\">";
_cs += "		<div class=\"logo\">";
_cs += "			<a href=\"index.html\"><img src=\"images/logo.jpg\" alt=\"拍拍店长\" /></a>";
_cs += "		</div>";
_cs += "		<div class=\"slogen\">";
_cs += "			<b>50万的拍拍店铺开店必备工具</b>";
_cs += "		</div>";
_cs += "		<div class=\"test\" id=\"nav_href\">";
_cs += "			<ul>";
_cs += "				<li class=\"current\"><a href=\"index.html\">首页</a></li>";
_cs += "				<li><a href=\"huiyuan.aspx\">会员营销</a></li>";
//_cs += "				<li><a href=\"home_yinxiao.jsp\">营销推广</a></li>";
//_cs += "				<li><a href=\"home_suzhu.jsp\">数据分析</a></li>";
//_cs += "				<li><a href=\"home_mouban.jsp\">店铺装修</a></li>";
//_cs += "				<li><a target=\"_blank\"";
//_cs += "					href=\"ProductUsingServlet?kind=8\">会员营销</a></li>";
//_cs += "				<li><a target=\"_blank\"";
//_cs += "					href=\"share.php\">经验分享</a></li>";
//_cs += "				<li><a target=\"_blank\" href=\"home_gold.jsp\">用户中心</a></li>";
_cs += "			</ul>";
_cs += "		</div>";
_cs += "	</div>";
_cs += "</div>";
_cs += "<div class=\"clear_height\"></div>";
_cs += "<div class=\"banner\" id=\"adv_banner\">";
_cs += "</div>";
document.write(_cs)
